name: Lint, Build, & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Lint
      run: script/lint
  build:
    name: Build
    runs-on: macos-${{ matrix.macos }}
    strategy:
      matrix:
        platform: [iOS, macOS, tvOS, watchOS]
        swift: [5.2, 5.3, 5.4, 5.5-dev]
        # The latest version of Xcode that supports each release of Swift.
        # https://developer.apple.com/support/xcode/
        include:
          - swift: 5.2
            xcode: 11.7
            macos: 10.15
          - swift: 5.3
            xcode: 12.4
            macos: latest
          - swift: 5.4
            pkg: https://swift.org/builds/swift-5.4.1-release/xcode/swift-5.4.1-RELEASE/swift-5.4.1-RELEASE-osx.pkg
            toolchain: swift
            macos: latest
          - swift: 5.5-dev
            pkg: https://swift.org/builds/swift-5.5-branch/xcode/swift-5.5-DEVELOPMENT-SNAPSHOT-2021-05-30-a/swift-5.5-DEVELOPMENT-SNAPSHOT-2021-05-30-a-osx.pkg
            toolchain: swift
            macos: latest
    env:
      TOOLCHAINS: ${{ matrix.toolchain }}
    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Select Xcode ${{ matrix.xcode }}
      if: ${{ matrix.xcode }}
      run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Install Swift ${{ matrix.swift }}
      if: ${{ matrix.pkg }}
      run: |
        curl -o swift.pkg '${{ matrix.pkg }}'
        sudo installer -pkg swift.pkg -target /
    - name: Build for macOS with Swift Package Manager
      if: ${{ matrix.platform == 'macOS' }}
      run: xcrun swift build --verbose
    - name: Build for ${{ matrix.platform }} with xcodebuild
      if: ${{ matrix.platform != 'macOS' }}
      run: xcrun xcodebuild build -scheme CombineCloudKit -destination generic/platform=${{ matrix.platform }}
  test:
    name: Test
    runs-on: macos-latest
    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Test
      run: xcrun swift test --verbose
  sanitize:
    name: Sanitize
    runs-on: macos-latest
    strategy:
      matrix:
        sanitizer: [address, thread, undefined]
    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Sanitize
      run: xcrun swift test --verbose --sanitize=${{ matrix.sanitizer }}
  codecov:
    name: Coverage
    runs-on: macos-latest
    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Coverage
      run: |
        xcrun swift test --verbose --enable-code-coverage
        cd .build/$(uname -m)-apple-macosx/debug
        xcrun llvm-cov show -use-color -instr-profile=codecov/default.profdata CombineCloudKitPackageTests.xctest/Contents/MacOS/CombineCloudKitPackageTests > coverage.txt
        bash <(curl -s https://codecov.io/bash) -f coverage.txt -Z
