name: Lint, Build, & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: script/lint
  build:
    name: Build
    runs-on: macos-${{ matrix.macos }}
    strategy:
      matrix:
        swift: [5.2, 5.3, 5.4, 5.5-dev]
        # The latest version of Xcode that supports each release of Swift.
        # https://developer.apple.com/support/xcode/
        include:
          - swift: 5.2
            xcode: 11.7
            macos: 10.15
          - swift: 5.3
            xcode: 12.4
            macos: latest
          - swift: 5.4
            # xcode: 12.5
            toolchain: https://swift.org/builds/swift-5.4.1-release/xcode/swift-5.4.1-RELEASE/swift-5.4.1-RELEASE-osx.pkg
            macos: latest
          - swift: 5.5-dev
            # xcode: 12.6
            toolchain: https://swift.org/builds/swift-5.5-branch/xcode/swift-5.5-DEVELOPMENT-SNAPSHOT-2021-05-30-a/swift-5.5-DEVELOPMENT-SNAPSHOT-2021-05-30-a-osx.pkg
            macos: latest
    steps:
    - uses: actions/checkout@v2
    - if: ${{ matrix.xcode }}
      run: |
        sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app
        xcrun swift build --verbose
    - if: ${{ matrix.toolchain }}
      run: |
        curl -o swift.pkg '${{ matrix.toolchain }}'
        sudo installer -pkg swift.pkg -target /
        xcrun --toolchain swift swift build --verbose
  test:
    name: Test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: xcrun swift test --verbose
  sanitize:
    name: Sanitize
    runs-on: macos-latest
    strategy:
      matrix:
        sanitizer: [address, thread, undefined]
    steps:
    - uses: actions/checkout@v2
    - run: xcrun swift test --verbose --sanitize=${{ matrix.sanitizer }}
  codecov:
    name: Coverage
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        xcrun swift test --verbose --enable-code-coverage
        cd .build/$(uname -m)-apple-macosx/debug
        xcrun llvm-cov show -use-color -instr-profile=codecov/default.profdata CombineCloudKitPackageTests.xctest/Contents/MacOS/CombineCloudKitPackageTests > coverage.txt
        bash <(curl -s https://codecov.io/bash) -f coverage.txt -Z
