name: Lint, Build, & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: script/lint
  build:
    name: Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: xcrun swift build --verbose
  test:
    name: Test
    runs-on: macos-latest
    strategy:
      matrix:
        sanitizer: [address, thread, undefined]
    steps:
    - uses: actions/checkout@v2
    - run: xcrun swift test --verbose --sanitize=${{ matrix.sanitizer }}
  codecov:
    name: Coverage
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        xcrun swift test --verbose --enable-code-coverage
        cd .build/$(uname -m)-apple-macosx/debug
        xcrun llvm-cov show -use-color -instr-profile=codecov/default.profdata CombineCloudKitPackageTests.xctest/Contents/MacOS/CombineCloudKitPackageTests > coverage.txt
        bash <(curl -s https://codecov.io/bash) -f coverage.txt -Z
